basePath: /api
definitions:
  device.DeviceDTO:
    properties:
      device_type:
        $ref: '#/definitions/device.DeviceTypeDTO'
      id:
        type: string
      location:
        $ref: '#/definitions/device.LocationDTO'
      name:
        type: string
      serial_number:
        type: string
    type: object
  device.DeviceTypeDTO:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  device.LocationDTO:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  err.Error:
    properties:
      error:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Restful API for the Northpole Shop
  license:
    name: MIT License
  title: NORTHPOLE-SHOP API
  version: "1.0"
paths:
  /devices:
    get:
      consumes:
      - application/json
      description: List devices
      parameters:
      - description: Start date
        in: query
        name: startTime
        type: integer
      - description: End date
        in: query
        name: endTime
        type: integer
      - description: Location UUID
        in: query
        name: locationId
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/device.DeviceDTO'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err.Error'
      summary: List devices
      tags:
      - devices
swagger: "2.0"
