services:

  app:
    build: .
    env_file:
      - "./.app.env"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    command: [ "sh", "-c", "/northpole-shop/bin/migrate up && /northpole-shop/bin/api" ]
    restart: always

  db:
    image: postgres:alpine
    env_file:
      - "./.app.env"
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 3s
      timeout: 5s
      retries: 5
    restart: always
volumes:
  data-volume:
